#pragma once
#include<map>
#include<vector>

using namespace std;


class AccountDictionary
{
public:
	AccountDictionary() { 		
		create_dictionary_box(); 
		set_dictionary(); 
		print_dictionary_from_map(); 
		print_dictionary_from_function(); 
		print_dictionary_index(); 
	};
	~AccountDictionary() {};

	struct dictionarybox	//Details of the sorting that occurs in the transaction.
	{
		int codeDeb;			//Code for debit account type code
		int class_codeDeb;		//class code of debit *unused
		int codeCre;			//Credit account type code
		int class_codeCre;		//Credit class code* unused
		
		char Debit[50];			//Debit subject code
		char Credit[50];		//Credit account name
		char Description[50];	//Description

	}*dic_box;


	struct dictionary_page		//A structure that combines the journal entries of the sender and recipient of the abstract into one coherent structure.
	{
		char transaction_name[50];							//Dictionary_index transaction name
		int sender_dictionary_entity_num;					//Number of journal entries required by the sender
		vector<dictionarybox*> sender_dictionary_entity;	//Location of actual required code entry.
		int receiver_dictionary_entity_num;					//Number of journal entries required to be processed by the recipient
		vector<dictionarybox*> receiver_dictionary_entity;	//Location of actual required code entry.
	}*dic_page;

	map<char*, int> dictionary_index;
	map<char*, int>::iterator dicin_it;
	map<char*, int>::iterator dicin_it2;
	map< int, dictionary_page*> dictionary;
	map< int, dictionary_page*>::iterator dic_it;
	map< int, dictionarybox*> dictionary_sentence;
	map< int, dictionarybox*>::iterator dic_sen;


	void create_dictionary_box()
	{
		int num;
		int code;
		int codeDeb, class_codeDeb, codeCre, class_codeCre;
		char Debit[100], Description[100], Credit[100];
		fscanf_s(simCont.SimConf->AccountSentence, "%d,", &num);
		for (int i = 0; i < num; i++)
		{

			fscanf_s(simCont.SimConf->AccountSentence, "%d,%d,%d,", &code, &codeDeb, &class_codeDeb);
			fscanf_s(simCont.SimConf->AccountSentence, "%[^,],%[^,],%[^,],", Debit, _countof(Debit), Description, _countof(Description), Credit, _countof(Credit));
			fscanf_s(simCont.SimConf->AccountSentence, "%d,%d,", &class_codeCre, &codeCre);
			create_dictionary_sentence(code, codeDeb, class_codeDeb, Debit, Description, Credit, class_codeCre, codeCre);
		}
	}

	void create_dictionary_sentence(int sentence_code, int codeDeb, int class_codeDeb, char* Debit, char* Description, char* Credit, int class_codeCre, int codeCre)
	{
		dic_box = new dictionarybox;
		dic_box->codeDeb = codeDeb;
		dic_box->class_codeDeb = class_codeDeb;
		strcpy_s(dic_box->Debit, _countof(dic_box->Debit), Debit);
		strcpy_s(dic_box->Description, _countof(dic_box->Description), Description);
		strcpy_s(dic_box->Credit, _countof(dic_box->Credit), Credit);
		dic_box->class_codeCre = class_codeCre;
		dic_box->codeCre = codeCre;

		dictionary_sentence.insert(pair<int, dictionarybox*>(sentence_code, dic_box));
	}



	//Dictionary writing area
	void set_dictionary()
	{
		int num = 0;
		int code;
		char name[100];
		int send_num;			//Number of journal entries generated by the sender
		int rece_num;			//Number of journal entries generated by recipients
		int send_code[10];		//Sender Code
		int rece_code[10];		//Recipient code
		fscanf_s(simCont.SimConf->AccountDictionary, "%d,", &num);
		for (int i = 0; i < num; i++)
		{
			fscanf_s(simCont.SimConf->AccountDictionary, "%d,%[^,],%d,%d,", &code, name, _countof(name), &send_num, &rece_num);
			for (int j = 0; j < send_num; j++)
			{
				fscanf_s(simCont.SimConf->AccountDictionary, "%d,", &send_code[j]);
			}

			for (int j = 0; j < rece_num; j++)
			{
				fscanf_s(simCont.SimConf->AccountDictionary, "%d,", &rece_code[j]);
			}
			create_dictionary(name, code, send_num, rece_num);
			for (int j = 0; j < send_num; j++)
				set_dictionary_box(0, code, send_code[j]);
			for (int j = 0; j < rece_num; j++)
				set_dictionary_box(1, code, rece_code[j]);

		}


	}



	//Get the number of journal entries from the relevant accounting relation from the dictionary_code_id and sendrece_code.
	int Get_Journalizing_number(int dictionary_code_id, int sendrece_code)
	{
		int amount = 0; 
		if (sendrece_code == 0)		amount = Get_dictionary_page(dictionary_code_id)->sender_dictionary_entity_num;
		else if (sendrece_code == 1)	amount = Get_dictionary_page(dictionary_code_id)->receiver_dictionary_entity_num;
		else simCont.ZZZF->stop_function("AccountDictionary::Get_shiwake_amount  A non-existent sendrece_code was entered.");
		return amount;
	}

	int Get_dictionary_id_code(const char* str)	//Find the index number (id_code) of the AccountDictionary from the accounting-related name (agents exchange this code).
	{
		
		dicin_it = dictionary_index.begin();
		for (int i = 0; i<int(dictionary_index.size()); i++)
		{
			if (strcmp(dicin_it->first, str) == 0)
			{
				break;
			}
			dicin_it++;
		}

		return dicin_it->second;
	}

	dictionary_page* Get_dictionary_page(int code) //Find Dictionary by index_code
	{
		dic_it = dictionary.find(code);
		if (dic_it == dictionary.end())
			simCont.ZZZF->stop_function("AccountDictionary::Get_dictionry_page@Searched for non-existent code.");
		return dic_it->second;
	}
	dictionarybox* Get_dictionary_box(int sentence_code)
	{
		dic_sen = dictionary_sentence.find(sentence_code);
		if (dic_sen == dictionary_sentence.end())
		{
			printf("code_test : %d\n", sentence_code); 
			simCont.ZZZF->stop_function("AccountDictionary::Get_dictionry_box@Searched for non-existent code.");
		}
		return dic_sen->second;
	}

	//Functions to retrieve actual accounting notations and codes.
	int Get_S_codeDeb(int code, int number) { return Get_dictionary_page(code)->sender_dictionary_entity[number]->codeDeb; }
	int Get_S_class_codeDeb(int code, int number) { return Get_dictionary_page(code)->sender_dictionary_entity[number]->class_codeDeb; }
	int Get_S_codeCre(int code, int number) { return Get_dictionary_page(code)->sender_dictionary_entity[number]->codeCre; }
	int Get_S_class_codeCre(int code, int number) { return Get_dictionary_page(code)->sender_dictionary_entity[number]->class_codeCre; }
	char* Get_S_Credit(int code, int number) { return Get_dictionary_page(code)->sender_dictionary_entity[number]->Credit; }
	char* Get_S_Debit(int code, int number) { return Get_dictionary_page(code)->sender_dictionary_entity[number]->Debit; }
	char* Get_S_Description(int code, int number) { return Get_dictionary_page(code)->sender_dictionary_entity[number]->Description; }

	int Get_R_codeDeb(int code, int number) { return Get_dictionary_page(code)->receiver_dictionary_entity[number]->codeDeb; }
	int Get_R_class_codeDeb(int code, int number) { return Get_dictionary_page(code)->receiver_dictionary_entity[number]->class_codeDeb; }
	int Get_R_codeCre(int code, int number) { return Get_dictionary_page(code)->receiver_dictionary_entity[number]->codeCre; }
	int Get_R_class_codeCre(int code, int number) { return Get_dictionary_page(code)->receiver_dictionary_entity[number]->class_codeCre; }
	char* Get_R_Credit(int code, int number) { return Get_dictionary_page(code)->receiver_dictionary_entity[number]->Credit; }
	char* Get_R_Debit(int code, int number) { return Get_dictionary_page(code)->receiver_dictionary_entity[number]->Debit; }
	char* Get_R_Description(int code, int number) { return Get_dictionary_page(code)->receiver_dictionary_entity[number]->Description; }



	void create_dictionary(char* transaction_name, int dictionary_code_id, int sender_num, int receiver_num)
	{
		char* name;
		dic_page = new dictionary_page;
		strcpy_s(dic_page->transaction_name, _countof(dic_page->transaction_name), transaction_name);
		dic_page->sender_dictionary_entity_num = sender_num;
		dic_page->receiver_dictionary_entity_num = receiver_num;
		dictionary.insert(pair<int, dictionary_page* >(dictionary_code_id, dic_page));

		name = (char*)malloc(strlen(transaction_name) + 1);
		strcpy_s(name, strlen(transaction_name) + 1, transaction_name);
		dictionary_index.insert(pair<char*, int>(name, dictionary_code_id));


	}
	void set_dictionary_box(int S_R_switch, int code_id, int sentence_code)
	{

		switch (S_R_switch)
		{
		case 0:		//Dictionary_box in the sender's side.
			Get_dictionary_page(code_id)->sender_dictionary_entity.push_back(Get_dictionary_box(sentence_code));
			break;
		case 1:		//Dictionary_box in the recipient's side.
			Get_dictionary_page(code_id)->receiver_dictionary_entity.push_back(Get_dictionary_box(sentence_code));
			break;
		default:
			simCont.ZZZF->stop_function("AccountDictionary::set_dictioary_box  Put the wrong S_R_switch in.\n");
		}
	}
	void check_dictionary(int code)
	{
		if (Get_dictionary_page(code)->sender_dictionary_entity_num != Get_dictionary_page(code)->sender_dictionary_entity.size())
			simCont.ZZZF->stop_function("AccountDictionary::check_dictionnary  Incorrect number of dicitonary created on the sender side of the code:%d.");
		if (Get_dictionary_page(code)->receiver_dictionary_entity_num != Get_dictionary_page(code)->receiver_dictionary_entity.size())
			simCont.ZZZF->stop_function("AccountDictionary::check_dictionnary  Incorrect number of dicitonary created on the receiver side of the code:%d.");
	}




	void print_dictionary_from_map()
	{
		char* str;
		fprintf(simCont.SimConf->zzz_account_dictionary, "Notation of Dictionary stored in map.\n");
		dic_it = dictionary.begin();
		fprintf(simCont.SimConf->zzz_account_dictionary,
			" , Debitcode , Debit class_code , Amount , Debit , Description , Credit , Amount , Creditclass_code , Creditcode ,  ,  , Debitcode , Debit class_code , Amount , Debit , Description , Credit , Amount , Creditclass_code , Creditcode\n");

		fprintf(simCont.SimConf->zzz_account_dictionary,
			" , receiver side, , , , , , , , , , , , sender side\n");
		for (int repeat = 0; repeat<int(dictionary.size()); repeat++)
		{//
			str = dic_it->second->transaction_name;
			fprintf(simCont.SimConf->zzz_account_dictionary,
				"Dictionary side code:,%d , Dictionary side name:,%s , number of sender's journal :,%d , number of receiver's journal:,%d\n"
				, dic_it->first, dic_it->second->transaction_name
				, dic_it->second->sender_dictionary_entity_num, dic_it->second->receiver_dictionary_entity_num);



			int repeat_num;
			repeat_num = simCont.ZZZF->comparison_int(dic_it->second->sender_dictionary_entity_num, dic_it->second->receiver_dictionary_entity_num);
			for (int i = 0; i < repeat_num; i++)
			{
				fprintf(simCont.SimConf->zzz_account_dictionary, "journalizing%d , ", i);
				if (i < dic_it->second->sender_dictionary_entity_num)
				{
					fprintf(simCont.SimConf->zzz_account_dictionary,
						"%d , %d , XXXXX , %s , %s , %s , XXXXX , %d , %d , , , "
						, dic_it->second->sender_dictionary_entity[i]->codeDeb
						, dic_it->second->sender_dictionary_entity[i]->class_codeDeb
						, dic_it->second->sender_dictionary_entity[i]->Debit
						, dic_it->second->sender_dictionary_entity[i]->Description
						, dic_it->second->sender_dictionary_entity[i]->Credit
						, dic_it->second->sender_dictionary_entity[i]->class_codeCre
						, dic_it->second->sender_dictionary_entity[i]->codeCre
					);
				}
				else fprintf(simCont.SimConf->zzz_account_dictionary, ", , , , , , , , , , ,");

				if (i < dic_it->second->receiver_dictionary_entity_num)
				{
					fprintf(simCont.SimConf->zzz_account_dictionary,
						"%d , %d , XXXXX , %s , %s , %s , XXXXX , %d , %d\n"
						, dic_it->second->receiver_dictionary_entity[i]->codeDeb
						, dic_it->second->receiver_dictionary_entity[i]->class_codeDeb
						, dic_it->second->receiver_dictionary_entity[i]->Debit
						, dic_it->second->receiver_dictionary_entity[i]->Description
						, dic_it->second->receiver_dictionary_entity[i]->Credit
						, dic_it->second->receiver_dictionary_entity[i]->class_codeCre
						, dic_it->second->receiver_dictionary_entity[i]->codeCre
					);
				}
				else fprintf(simCont.SimConf->zzz_account_dictionary, "\n");
			}
			dic_it++;
			fprintf(simCont.SimConf->zzz_account_dictionary, "\n");
		}
		fprintf(simCont.SimConf->zzz_account_dictionary, "\n\n\n");
	}

	void print_dictionary_from_function()
	{
		fprintf(simCont.SimConf->zzz_account_dictionary, "Notation of Dictionary taken from a function.\n");
		dic_it = dictionary.begin();
		fprintf(simCont.SimConf->zzz_account_dictionary,
			" , , , Receiver side, , , , , , , , , , , , Sender side\n");
		fprintf(simCont.SimConf->zzz_account_dictionary,
			" , , , Debt code , Debt class_code , Amount , Debt , Description , Credit , Amount , Credit class_code , Credit code ,  ,  , Debt code , Debt class_code , Amount , Debt , Description , Credit , Amount , Credit class_code , Credit code\n");

		for (int repeat = 0; repeat<int(dictionary.size()); repeat++)
		{
			fprintf(simCont.SimConf->zzz_account_dictionary,
				"Dictionary side code:,%d , Dictionary side name:,%s , number of sender's journal :,%d , number of receiver's journal:,%d\n"
				, dic_it->first, dic_it->second->transaction_name
				, dic_it->second->sender_dictionary_entity_num, dic_it->second->receiver_dictionary_entity_num);


			int repeat_num;
			repeat_num = simCont.ZZZF->comparison_int(dic_it->second->sender_dictionary_entity_num, dic_it->second->receiver_dictionary_entity_num);
			for (int i = 0; i < repeat_num; i++)
			{
				fprintf(simCont.SimConf->zzz_account_dictionary, " , journalizing%d , , ", i);
				if (i < dic_it->second->sender_dictionary_entity_num)
				{
					fprintf(simCont.SimConf->zzz_account_dictionary,
						"%d , %d , XXXXX , %s , %s , %s , XXXXX , %d , %d , , , "
						, Get_S_codeDeb(dic_it->first, i)					
						, Get_S_class_codeDeb(dic_it->first, i)				
						, Get_S_Debit(dic_it->first, i)					
						, Get_S_Description(dic_it->first, i)		
						, Get_S_Credit(dic_it->first, i)				
						, Get_S_class_codeCre(dic_it->first, i)			
						, Get_S_codeCre(dic_it->first, i)			
					);
				}
				else fprintf(simCont.SimConf->zzz_account_dictionary, ", , , , , , , , , , ,");

				if (i < dic_it->second->receiver_dictionary_entity_num)
				{
					fprintf(simCont.SimConf->zzz_account_dictionary,
						"%d , %d , XXXXX , %s , %s , %s , XXXXX , %d , %d\n"
						, Get_R_codeDeb(dic_it->first, i)			
						, Get_R_class_codeDeb(dic_it->first, i)		
						, Get_R_Debit(dic_it->first, i)				
						, Get_R_Description(dic_it->first, i)		
						, Get_R_Credit(dic_it->first, i)			
						, Get_R_class_codeCre(dic_it->first, i)		
						, Get_R_codeCre(dic_it->first, i)			
					);
				}
				else fprintf(simCont.SimConf->zzz_account_dictionary, "\n");
			}
			dic_it++;
			fprintf(simCont.SimConf->zzz_account_dictionary, "\n");
		}
	}
	void print_dictionary_index()
	{
		map<int, char*> temp_index;
		map<int, char*>::iterator temp_it;
		dicin_it = dictionary_index.begin();
		for (int repeat = 0; repeat<int(dictionary_index.size()); repeat++)
		{
			fprintf(simCont.SimConf->zzz_account_dictionary, "%s,%d\n", dicin_it->first, dicin_it->second);
			dicin_it++;
		}
	}
};



